server:
  port: 8080

spring:
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest
    #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调
    publisher-confirm-type: correlated
    #保证交换机能把消息推送到队列中
    publisher-returns: true
    virtual-host: url-access-vh
    #这个配置是保证消费者会消费消息，手动确认
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true
  application:
    name: chat-service
  web:
    locale: en_US
  jackson:
    default-property-inclusion: non_null
    time-zone: America/New_York
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery: # 服务发现配置
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        health-check-path: /health
        heartbeat:
          enabled: true
  datasource:
    url: jdbc:postgresql://dpg-cminr5mg1b2c73d65hgg-a.oregon-postgres.render.com/chatting_h8k0
    username: chatting_h8k0_user
    password: 3HiVek6CuR9TKAYWPN4ZUbZ0NEESR9II
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
