server:
  port: 8083

spring:
  application:
    name: message-consumer-service
  web:
    locale: en_US
  jackson:
    default-property-inclusion: non_null
    time-zone: America/New_York
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery: # 服务发现配置
        enabled: true
        register: true
        deregister: true
        prefer-ip-address: true
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        health-check-path: /health
        heartbeat:
          enabled: true
  rabbitmq:
    port: 5672
    host: 192.168.1.67
    username: admin
    password: james
    #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调
    publisher-confirm-type: correlated
    #保证交换机能把消息推送到队列中
    publisher-returns: true
    virtual-host: url-access-vh
    #这个配置是保证消费者会消费消息，手动确认
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true
  elasticsearch:
    uris: http://127.0.0.1:9200